{% set name = "signac-flow" %}
{% set version = "0.6.2" %}
{% set sha256 = "7325400faae005a9144d19866228b9d3990c01652bf2d670e281b16aa6616be0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/glotzer/signac-flow/get/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - enum34  # [py27]
    - jinja2 >=2.8
  run:
    - python
    - enum34  # [py27]
    - signac
    - jinja2 >=2.8

test:
  imports:
    - flow

about:
  home: http://glotzerlab.engin.umich.edu/signac
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Project workflow management for signac projects.'
  description: |
    The signac-flow tool provides the basic components to setup simple to
    complex workflows for signac projects. That includes the definition of
    data pipelines, execution of data space operations and the submission
    of operations to high-performance super computers.
    The implementation is in pure Python, requires signac and is tested for
    Python versions 2.7 and 3.4+.
  doc_url: https://signac-flow.readthedocs.io
  dev_url: https://bitbucket.org/glotzer/signac-flow

extra:
  recipe-maintainers:
    - csadorf
