{% set version = "0.27.0" %}

package:
  name: signac-flow
  version: {{ version }}

source:
  url: https://github.com/glotzerlab/signac-flow/archive/v{{ version }}.tar.gz
  sha256: c864da7f25f73d6dabcbfa9d558feef45b46cc8e5a0c491a757f79e7a747c08b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - flow = flow.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - cloudpickle >=1.6.0
    - deprecation >=2.0.0
    - jinja2 >=3.0.0
    - jsonschema >=3.0.0
    - python >=3.8
    - signac >=2.0.0
    - tqdm >=4.60.0

test:
  imports:
    - flow

about:
  home: https://signac.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Workflow management for signac projects.
  description: |
    The signac-flow tool provides the basic components to setup simple to
    complex workflows for signac projects. That includes the definition of
    data pipelines, execution of data space operations and the submission
    of operations to high-performance super computers.
  doc_url: https://docs.signac.io
  dev_url: https://github.com/glotzerlab/signac-flow

extra:
  recipe-maintainers:
    - cbkerr
    - joaander
    - bdice
    - csadorf
    - mikemhenry
    - vyasr
    - b-butler
